name: Trigger private repo sync

on:
  push:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger private repo sync
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
            https://api.github.com/repos/Vyrotris/Aval-Private/dispatches \
            -d '{"event_type":"sync_public_to_private"}'
